"""build_agent.py -- Compose main.py's route+core pipeline with overlays.py's
revived market-intelligence overlays, driven by a single params vector (see
tuning_spec.py). Two use modes:

  1. In-process (used by evolve.py's fitness evaluation): call
     make_agent(params_vector) to get a live agent(obs) callable in the
     current Python process. Cheap -- no file I/O.

  2. Materialize a standalone candidate file (for benchmark.py CLI /
     `kaggle competitions submit`): write_candidate(params_vector, out_path)
     writes a self-contained .py that imports main.py + overlays.py from the
     same directory and defines agent()/`_kaggle_submission_entrypoint`,
     exactly like every other MapleLeaf version.

The default params vector (tuning_spec.default_vector()) reproduces main.py's
current (6.5) behavior exactly -- every revived overlay defaults OFF, so a
freshly-cloned repo with no tuning run yet behaves identically to the shipped
agent. Only a CMA-ES-discovered vector that wins a real benchmark should ever
be promoted into main.py itself.
"""

import os

import tuning_spec


def make_agent(params_vector):
    """Returns a live agent(obs) function combining main.py + overlays.py,
    configured with the given params vector. Mutates both modules' shared
    global state (main._BASE_PARAMS, main._FR_ITEMS, overlays._P) -- callers
    running many candidates in one process must call this again (or re-import)
    before evaluating a different candidate; safe within a single process
    since main.agent()'s own per-episode state dicts self-reset on step==0."""
    import main as _base
    import overlays

    base_params, overlay_params, fr_order = tuning_spec.vector_to_params(params_vector)
    _base.configure_base(base_params)
    _base._FR_ITEMS = fr_order
    overlays.configure(overlay_params)

    def agent(obs):
        try:
            step = min(max(0, int(_base._get(obs, "step", 0) or 0)), len(_base._ACTIONS) - 1)
            action = _base._weed_repair_action(obs, _base._copy_action(_base._ACTIONS[step]), step)
            state = _base._fr_state(obs, step)
            action = _base._repay(action, state, step)
            action = overlays.repay_premium_shift(obs, action, step)
            action = overlays.repay_fertilizer_relay(obs, action, step)
            action = _base._front_run(action, obs, state, step)
            overlays._detect_opponent_type(obs, step)
            action = overlays.price_floor_guard(obs, action, step)
            action = overlays.rank_sell_slots(obs, action)
            action = overlays.premium_shift(obs, action, step, _base._ACTIONS)
            action = overlays.fertilizer_relay(obs, action, step, _base._ACTIONS)
            action = overlays.opportunistic_sell(obs, action, step)
            action = overlays.terminal_liquidation(obs, action, step)
            return _base._align_hands(action, obs)
        except Exception:
            farm = _base._farm(obs, _base._seat(obs))
            return {
                "farmer": ["PASS"],
                "hands": [["PASS"] for _ in (_base._get(farm, "hands", []) or [])],
                "market": [],
            }

    return agent


_CANDIDATE_TEMPLATE = '''"""MapleLeaf 6.6 candidate -- generated by build_agent.py, do not hand-edit.

Composed from main.py's route + core overlays plus overlays.py's revived
market-intelligence overlays, configured with the params vector below (found
by evolve.py's CMA-ES search). See tuning_spec.py for what each name means.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import build_agent

PARAMS_VECTOR = {params_vector!r}

agent = build_agent.make_agent(PARAMS_VECTOR)


def _kaggle_submission_entrypoint(obs, configuration=None):
    return agent(obs)
'''


def write_candidate(params_vector, out_path):
    with open(out_path, "w") as f:
        f.write(_CANDIDATE_TEMPLATE.format(params_vector=list(params_vector)))
    return out_path


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--from-checkpoint", default="evolve_checkpoint.json",
                     help="Read best params vector from this evolve.py checkpoint")
    ap.add_argument("--out", default="/tmp/candidate.py")
    ap.add_argument("--default", action="store_true", help="Use tuning_spec defaults instead")
    args = ap.parse_args()

    if args.default:
        vec = tuning_spec.default_vector()
    else:
        import json
        with open(args.from_checkpoint) as f:
            ckpt = json.load(f)
        vec = ckpt["best_params"]
    write_candidate(vec, args.out)
    print(f"Wrote candidate -> {args.out}")
